# Generated by Django 4.2.1 on 2023-05-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banco",
            name="tasa",
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
    ]
