# Generated by Django 4.2.1 on 2023-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_banco_tasa"),
    ]

    operations = [
        migrations.AddField(
            model_name="banco",
            name="rgb",
            field=models.CharField(default="default_value", max_length=10),
        ),
    ]
